Repository projectsyn/component-keycloak, pull requests merged in 2021-12, with the labels that each got.

#102 Update to Helm v3 parameters
  class/defaults.yml
  class/keycloak.yml
  component/prometheus-netpol.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: bug

#90 Add support for OpenShift service serving certs
  class/defaults.yml
  component/main.jsonnet
  docs/modules/ROOT/pages/how-tos/keycloak-tls.adoc
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/openshift/openshift/apps/openshift.yaml
  tests/golden/openshift/openshift/openshift/00_namespace.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloak/templates/configmap-startup.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloak/templates/ingress.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloak/templates/prometheusrule.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloak/templates/service-headless.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloak/templates/service-http.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloak/templates/serviceaccount.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloak/templates/servicemonitor.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloak/templates/statefulset.yaml
  tests/golden/openshift/openshift/openshift/10_admin_secret.yaml
  tests/golden/openshift/openshift/openshift/11_db_secret.yaml
  tests/openshift.yml
Labels: enhancement

#103 Use Openshift Service serving cert as recommended default
  docs/modules/ROOT/pages/how-tos/openshift-4.adoc
Labels: documentation

#104 Replace static version label with image tag v15.0.2
  class/defaults.yml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloak/charts/postgresql/templates/statefulset.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloak/templates/configmap-startup.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloak/templates/ingress.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloak/templates/prometheusrule.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloak/templates/service-headless.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloak/templates/service-http.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloak/templates/serviceaccount.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloak/templates/servicemonitor.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloak/templates/statefulset.yaml
  tests/golden/builtin/builtin/builtin/10_admin_secret.yaml
  tests/golden/builtin/builtin/builtin/11_db_secret.yaml
  tests/golden/builtin/builtin/builtin/12_db_certs.yaml
  tests/golden/builtin/builtin/builtin/13_keycloak_certs.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloak/templates/configmap-startup.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloak/templates/ingress.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloak/templates/prometheusrule.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloak/templates/service-headless.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloak/templates/service-http.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloak/templates/serviceaccount.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloak/templates/servicemonitor.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloak/templates/statefulset.yaml
  tests/golden/external/external/external/10_admin_secret.yaml
  tests/golden/external/external/external/11_db_secret.yaml
  tests/golden/external/external/external/12_db_certs.yaml
  tests/golden/external/external/external/13_keycloak_certs.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloak/templates/configmap-startup.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloak/templates/ingress.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloak/templates/prometheusrule.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloak/templates/service-headless.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloak/templates/service-http.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloak/templates/serviceaccount.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloak/templates/servicemonitor.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloak/templates/statefulset.yaml
  tests/golden/openshift/openshift/openshift/10_admin_secret.yaml
  tests/golden/openshift/openshift/openshift/11_db_secret.yaml
  tests/openshift.yml
Labels: change

#106 Fix backup command for builtin PostgreSQL DB
  class/defaults.yml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloak/charts/postgresql/templates/statefulset.yaml
Labels: bug

#95 Add how-to page to backup and restore Keycloak
  docs/modules/ROOT/pages/how-tos/restore.adoc
  docs/modules/ROOT/pages/how-tos/use-built-in-db.adoc
  docs/modules/ROOT/partials/nav.adoc
Labels: documentation
