Repository projectsyn/component-keycloak, pull requests merged in 2021-11, with the labels that each got.

#85 Fix wrong indentation in the docs for OCP how-to
  docs/modules/ROOT/pages/how-tos/openshift-4.adoc
Labels: documentation

#84 Document & test multiple themes
  class/defaults.yml
  class/keycloak.yml
  docs/modules/ROOT/pages/how-tos/custom-theme.adoc
  docs/modules/ROOT/pages/how-tos/db-tls.adoc
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/builtin.yml
  tests/builtin/statefulset_keycloak_test.go
  tests/external.yml
  tests/external/statefulset_keycloak_test.go
Labels: documentation, hacktoberfest-accepted

#86 Add description for default themes in extraEnv
  docs/modules/ROOT/pages/how-tos/custom-theme.adoc
Labels: documentation

#88 Generate Ingress with `apiVersion: networking.k8s.io/v1`
  class/keycloak.yml
  docs/modules/ROOT/pages/index.adoc
  postprocess/api_version.jsonnet
  tests/builtin/ingress_test.go
  tests/common/apiversion.go
  tests/external/ingress_test.go
Labels: change

#89 Ensure OpenShift Routes use correct TLS termination
  class/defaults.yml
Labels: bug

#91 Reduce duplication in defaults
  class/defaults.yml
Labels: change

#92 Remove unused ACME annotation
  class/defaults.yml
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: change

#96 Separate internal and external TLS config
  class/defaults.yml
  component/main.jsonnet
  docs/modules/ROOT/pages/how-tos/upgrade-5.x-to-6.x.adoc
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/external.yml
Labels: breaking

#98 Use correct TLS provider config
  class/defaults.yml
Labels: bug
