Repository projectsyn/component-keycloak, pull requests merged in 2021-08, with the labels that each got.

#42 Update tests for latest Commodore version
  Makefile
  tests/builtin.yml
  tests/builtin/secrets_test.go
  tests/external.yml
  tests/external/postgresql_helmchart_not_rendered_test.go
  tests/external/secrets_test.go
Labels: change

#41 Patch apiVersion in postgresql helm chart
  class/keycloak.yml
  postprocess/api_version.jsonnet
  tests/builtin/statefulset_postgres_test.go
  tests/common/boilerplate.go
Labels: bug

#43 Add guide how to install on OCP4
  component/app.jsonnet
  docs/modules/ROOT/pages/how-tos/openshift-4.adoc
  docs/modules/ROOT/partials/nav.adoc
Labels: documentation

#45 Add synmonitoring label to namespace
  class/keycloak.yml
  component/main.jsonnet
  component/prometheus-netpol.jsonnet
Labels: bug
