Repository projectsyn/component-keycloak, pull requests merged in 2021-06, with the labels that each got.

#20 Disable network policy for Keycloak by default
  class/defaults.yml
  component/main.jsonnet
  docs/modules/ROOT/pages/explanations/default-features.adoc
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: breaking

#21 Add upgrade guide for 3.x
  docs/modules/ROOT/pages/how-tos/upgrade-2.x-to-3.x.adoc
  docs/modules/ROOT/partials/nav.adoc
Labels: documentation

#14 Encrypt cluster-internal traffic
  class/defaults.yml
  component/main.jsonnet
  docs/modules/ROOT/pages/explanations/default-features.adoc
  docs/modules/ROOT/pages/how-tos/configure-ingress.adoc
  docs/modules/ROOT/pages/how-tos/keycloak-tls.adoc
  docs/modules/ROOT/pages/how-tos/multi-instance.adoc
  docs/modules/ROOT/pages/references/parameters.adoc
  docs/modules/ROOT/pages/tutorials/installation.adoc
  docs/modules/ROOT/partials/nav.adoc
  tests/external.yml
Labels: breaking

#24 Add upgrade instructions from v3 to v4
  docs/modules/ROOT/pages/how-tos/upgrade-3.x-to-4.x.adoc
Labels: documentation

#26 Add Modulesync support
  .github/workflows/test.yaml
  .sync.yml
  Makefile
  Makefile.custom.mk
  Makefile.vars.mk
  docs/modules/ROOT/pages/explanations/default-features.adoc
  docs/modules/ROOT/pages/how-tos/configure-ingress.adoc
  docs/modules/ROOT/pages/how-tos/upgrade-2.x-to-3.x.adoc
  docs/modules/ROOT/pages/how-tos/upgrade-3.x-to-4.x.adoc
  docs/modules/ROOT/pages/references/parameters.adoc
  docs/modules/ROOT/pages/tutorials/installation.adoc
Labels: change
