Repository projectsyn/component-keycloak, pull requests merged in 2022-12, with the labels that each got.

#187 Fix NetworkPolicy keycloakx-infinispan is not conditional to networkPolicy.enabled
  component/main.jsonnet
  tests/golden/builtin/builtin/builtin/01_networkpolicy_infinispan.yaml
  tests/golden/external/external/external/01_networkpolicy_infinispan.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_networkpolicy_infinispan.yaml
  tests/golden/openshift/openshift/openshift/01_networkpolicy_infinispan.yaml
Labels: bug

#176 Remove K8up v1 annotations
  class/defaults.yml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
Labels: breaking

#192 Update Ingress NGINX network policy configuration for K8s >= 1.21
  class/defaults.yml
  component/main.jsonnet
Labels: breaking

#180 Upgrade to postgresql to 11.17.0-debian-11-r37
  class/defaults.yml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
Labels: dependency

#175 Update Keycloak to v19
  class/defaults.yml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
Labels: dependency

#196 Upgrade Postgres helm chart to v12.1.3
  class/defaults.yml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/networkpolicy.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/networkpolicy.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/svc-headless.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/svc.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/networkpolicy.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/svc-headless.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/svc.yaml
Labels: dependency

#197 Update Helm release keycloakx to v1.7.0
  class/defaults.yml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/networkpolicy.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
Labels: dependency

#191 Upgrade from v10 to v11
  docs/modules/ROOT/pages/how-tos/upgrade-10.x-to-11.x.adoc
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/partials/nav.adoc
Labels: documentation

#200 Fix Upgrade 10.x to 11.x test and navigation link
  docs/modules/ROOT/pages/how-tos/upgrade-10.x-to-11.x.adoc
  docs/modules/ROOT/partials/nav.adoc
Labels: bug
