Repository projectsyn/component-keycloak, pull requests merged in 2023-06, with the labels that each got.

#214 Remove SYNMonitoring and add labels for OpenShift and component-prometheus
  component/main.jsonnet
  tests/builtin.yml
  tests/builtin/namespace_test.go
  tests/external.yml
  tests/golden/builtin/builtin/builtin/00_namespace.yaml
  tests/golden/external/external/external/00_namespace.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/00_namespace.yaml
  tests/golden/openshift/openshift/openshift/00_namespace.yaml
  tests/openshift-postgres.yml
  tests/openshift-postgres/namespace_test.go
  tests/openshift.yml
  tests/openshift/namespace_test.go
Labels: change

#210 Update keycloak
  class/defaults.yml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/networkpolicy.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/networkpolicy.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/svc-headless.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/svc.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/networkpolicy.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/svc-headless.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/svc.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
Labels: dependency

#215 Fix monitoring network policy to use component-prometheus
  component/prometheus-netpol.jsonnet
  tests/golden/builtin/builtin/builtin/40_netpol.yaml
Labels: bug

#221 Fix wrong provider parameter for ingress when using vault
  component/main.jsonnet
Labels: bug

#222 Fix wrong type of tls secret for ingress object when using provider vault
  component/main.jsonnet
Labels: bug

#218 Add Keycloak Pod Security Admission documentation for OpenShift 4
  docs/modules/ROOT/pages/how-tos/custom-theme.adoc
  docs/modules/ROOT/pages/how-tos/openshift-4.adoc
Labels: enhancement
