Repository projectsyn/component-keycloak, pull requests merged in 2025-05, with the labels that each got.

#317 Update Helm release keycloakx to v2.6.0
  class/defaults.yml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/networkpolicy.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/networkpolicy.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/networkpolicy.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/networkpolicy.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
Labels: dependency

#315 Update docker.io/bitnami/postgresql Docker tag to v15.10.0-debian-12-r2
  class/defaults.yml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
Labels: dependency

#295 Update quay.io/keycloak/keycloak Docker tag to v26
  class/defaults.yml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/networkpolicy.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/networkpolicy.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/networkpolicy.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/networkpolicy.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
Labels: dependency

#330 How to Upgrade from v18 to v19
  docs/modules/ROOT/pages/how-tos/upgrade-18.x-to-19.x.adoc
  docs/modules/ROOT/partials/nav.adoc
Labels: breaking

#333 Update quay.io/keycloak/keycloak Docker tag to v26.2.4
  class/defaults.yml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/networkpolicy.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/networkpolicy.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
  tests/golden/external/external/external/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/networkpolicy.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/ingress.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/networkpolicy.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/prometheusrule.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/service-headless.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/service-http.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/serviceaccount.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/servicemonitor.yaml
  tests/golden/openshift/openshift/openshift/01_keycloak_helmchart/keycloakx/templates/statefulset.yaml
Labels: dependency, automerge, bump:patch

#334 Update docker.io/bitnami/os-shell Docker tag to v12-debian-12-r44
  class/defaults.yml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
Labels: dependency, automerge, bump:patch

#336 Update docker.io/bitnami/os-shell Docker tag to v12-debian-12-r45
  class/defaults.yml
  tests/golden/builtin/builtin/builtin/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
  tests/golden/openshift-postgres/openshift-postgres/openshift-postgres/01_keycloak_helmchart/postgresql/templates/primary/statefulset.yaml
Labels: dependency, automerge, bump:patch
